# Site settings
title: Foundry
description: Shared Creative Space for Artists and Creative professionals.
keywords: Coworking, Corvallis, Create, Make, Art, Studio, Space
author:
baseurl: "home" # the subpath of your site, e.g. /blog/
url: "thefoundryhq.com" # the base hostname & protocol for your site
